# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bebfb1c712dacc66b2659790c9ce09c9ee0eb48ce376285a74d0b8c9e3bf4cb9021984835a8b0b79bc8919cb6ebfc213fc694072d2855b51df049587b63f100

test:
  secret_key_base: 9261c7bc0cd28dcd155d5486d99e615d0cbde44cd03d507e99ece5e61081f5dba0ad001b501d40e08356bf03b9eb8df710479fc7bcf954dc0627845a3ac34232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
